# Generated by Django 5.2.4 on 2025-07-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlqueue',
            name='referrer',
            field=models.URLField(blank=True, help_text='URL desde donde se hizo el request (HTTP Referrer)', max_length=2048),
        ),
    ]
