# Generated by Django 5.2.4 on 2025-08-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_urlqueue_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlresult',
            name='content_extracted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de extracción del contenido', null=True),
        ),
        migrations.AddField(
            model_name='crawlresult',
            name='content_length',
            field=models.IntegerField(default=0, help_text='Número de caracteres del contenido completo'),
        ),
        migrations.AddField(
            model_name='crawlresult',
            name='full_content',
            field=models.TextField(blank=True, help_text='Contenido completo extraído del archivo (máximo 1M caracteres)', null=True),
        ),
        migrations.AlterField(
            model_name='crawlsession',
            name='max_pages',
            field=models.IntegerField(default=0, help_text='Máximo número de páginas a crawlear (0 = sin límite)'),
        ),
    ]
